# Generated by Django 5.0.6 on 2024-05-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('age', models.IntegerField()),
                ('date_of_entry', models.DateField()),
                ('date_of_departure', models.DateField(blank=True, null=True)),
                ('departure_zoo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'animal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnimalPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_residence', models.DateField()),
                ('end_residence', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'animal_place',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cages',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_warm', models.BooleanField()),
            ],
            options={
                'db_table': 'cages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CagesNeighbours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'cages_neighbours',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompatibleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'compatible_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'food',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FoodSeller',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('weight', models.IntegerField()),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'food_seller',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HowEat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('age_from', models.IntegerField()),
                ('age_to', models.IntegerField()),
            ],
            options={
                'db_table': 'how_eat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Offspring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'offspring',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResponsibilityForAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'responsibility_for_animal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'sellers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('predator', models.BooleanField()),
                ('need_warm', models.BooleanField()),
            ],
            options={
                'db_table': 'type_animal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VaccinationsAndDiseases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'vaccinations_and_diseases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('wages', models.IntegerField()),
                ('male', models.BooleanField()),
                ('age', models.IntegerField()),
                ('profession', models.TextField()),
                ('date_appointment', models.DateField()),
                ('date_layoff', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workers',
                'managed': False,
            },
        ),
    ]
